const {test}=require('node:test'),assert=require('node:assert/strict'),H=require('../staff-attendance-history.js');
const m={id:'san',module:'indoorStaffMaster',indoor_staff_name:'Sanju_Ofc',joining_date:'2026-10-01',status:'In Progress'},user={name:'Sanju',role:'Indoor'};
const attendance=(id,date,status,more={})=>({id,module:'attendance',master_id:'san',employee_name:'Sanju_Ofc',date,attendance_status:status,approval_status:'Approved',updatedAtMs:1,...more});
test('history keeps four punches, one salary day, approval reason and record references',()=>{const r=attendance('punch','2026-10-06','Present',{punch_sessions:[{label:'Morning',punch_in:'10:00',punch_out:'14:30',working_minutes:270},{label:'Evening',punch_in:'18:00',punch_out:'22:00',working_minutes:240}],working_minutes:510}),a=attendance('abs','2026-10-05','Absent',{remarks:'Office approved absence'});const data=H.report([m,r,a],user,'2026-10','2026-10-06');assert.equal(data.totals.punchIn,2);assert.equal(data.totals.punchOut,2);assert.equal(data.totals.absent,1);assert.equal(data.totals.present,5);assert.equal(data.totals.minutes,510);const html=H.html(data);for(const time of ['10:00','14:30','18:00','22:00'])assert.ok(html.includes(time));assert.ok(html.includes('Office approved absence'));assert.ok(H.html(data,'Absent').includes('Reference')||H.html(data,'Absent').includes('reference'));assert.ok(!H.html(data,'Absent').includes('22:00'));});
test('pending/rejected requests never change effective attendance and no punch evidence is invented',()=>{const pending=attendance('pending','2026-10-01','Absent',{source_app:'staffPortal',approval_status:'Pending Approval'}),rejected={...pending,id:'rejected',approval_status:'Rejected'};const data=H.report([m,pending,rejected],user,'2026-10','2026-10-01');assert.equal(data.totals.absent,0);assert.equal(data.days[0].automatic,true);assert.equal(data.days[0].requests.length,2);assert.equal(data.totals.punchIn,0);assert.match(H.html(data),/no saved attendance record or punch evidence/);assert.match(H.html(data),/Pending Approval/);});
test('approved leave ranges, restored Present and reactivation gaps match company-effective rules',()=>{const mm={...m,reactivation_date:'2026-10-05',employment_periods:[{start:'2026-10-01',end:'2026-10-02'}]},leave={id:'leave',module:'leaveApproval',master_id:'san',leave_from:'2026-10-05',leave_to:'2026-10-06',approval_status:'Approved',reason:'Medical',updatedAtMs:2};const restored=attendance('restore','2026-10-06','Restore Present',{updatedAtMs:3});const data=H.report([mm,leave,restored],user,'2026-10','2026-10-06');assert.equal(data.days.length,4);assert.equal(data.totals.leave,1);assert.equal(data.days[0].status,'Present');assert.ok(!data.days.some(d=>d.date==='2026-10-03'));});
test('each login sees only its own master and rows, including Driver and Worker histories',()=>{const other={...m,id:'sw',indoor_staff_name:'Swagatika'},secret=attendance('secret','2026-10-01','Absent',{master_id:'sw',employee_name:'Swagatika',remarks:'PRIVATE_OTHER_STAFF'});assert.ok(!H.html(H.report([m,other,secret],user,'2026-10','2026-10-01')).includes('PRIVATE_OTHER_STAFF'));for(const [module,field,role]of [['driverMaster','driver_name','Driver'],['workerMaster','worker_name','Worker']]){const master={id:module,module,[field]:'Ajay',joining_date:'01/10/2026'},r={id:'x',module:'attendance',master_id:module,date:'01/10/2026',attendance_status:'Absent'};assert.equal(H.report([master,r],{name:'Ajay',role},'2026-10','2026-10-01').totals.absent,1);}assert.throws(()=>H.report([m,{...m,id:'dup'}],user,'2026-10','2026-10-01'));});
test('history escapes record text and excludes future/after-inactive days',()=>{const inactive={...m,status:'Inactive',inactive_date:'2026-10-02'},r=attendance('unsafe','2026-10-01','Absent',{remarks:'<img src=x onerror=alert(1)>'});const data=H.report([inactive,r],user,'2026-10','2026-10-07');assert.equal(data.days.length,2);assert.ok(!H.html(data).includes('<img'));assert.ok(H.html(data).includes('&lt;img'));assert.equal(H.report([m],user,'2026-11','2026-10-07').days.length,0);});
test('later company absence record does not hide already saved punch evidence',()=>{const p=attendance('saved-punch','2026-10-01','Present',{punch_in:'10:00',punch_out:'14:30',working_minutes:270,updatedAtMs:1}),a=attendance('company-absent','2026-10-01','Absent',{remarks:'Company decision',updatedAtMs:2});const data=H.report([m,p,a],user,'2026-10','2026-10-01');assert.equal(data.days[0].status,'Absent');assert.equal(data.days[0].punchRecord.id,'saved-punch');assert.equal(data.totals.punchIn,1);const html=H.html(data);assert.match(html,/company-absent/);assert.match(html,/saved-punch/);assert.match(html,/14:30/);});

test('saved absence note takes priority over legacy remarks and is escaped',()=>{const r=attendance('absence-note','2026-10-01','Absent',{note:'Medical appointment <confirmed>',remarks:'Old remark'});const html=H.html(H.report([m,r],user,'2026-10','2026-10-01'),'Absent');assert.match(html,/Medical appointment &lt;confirmed&gt;/);assert.ok(!html.includes('Old remark'));});
