const {test}=require('node:test');const assert=require('node:assert/strict');
const docs=require('../vehicle-documents.js');const store=require('../vehicle-documents-store.js');
const photo={name:'Front',blob:new Blob(['photo'],{type:'image/jpeg'})};
const valid={document_type:'RC',document_name:'RC',vehicle_number:'OD-05-AP-9537',no_expiry:true,driver_name:''};
test('vehicle matching tolerates spaces, but rejects unassigned vehicles',()=>{assert.equal(docs.key('OD 05 AP 9537'),docs.key('OD-05-AP-9537'));assert.throws(()=>docs.validate(valid,[photo],['OD05BD8855'],['Somnath']),/not assigned/);});
test('licence stays attached to driver, never a reassigned vehicle',()=>{const rows=[{record_type:'vehicleDocumentV1',document_type:'Driving Licence',driver_name:'Ajay',vehicle_number:'OD05AP9537'},{record_type:'vehicleDocumentV1',document_type:'RC',vehicle_number:'OD 05 AP 9537'}];assert.equal(docs.visible(rows,'OD05AP9537','Somnath').length,1);});
test('pending renewal does not replace a verified original; newest verified becomes current',()=>{const old={id:'old',document_type:'RC',verification_status:'Verified',created_ms:1},pending={id:'new',document_type:'RC',verification_status:'Pending',created_ms:2};assert.equal(docs.groups([pending,old])[0].current.id,'old');assert.equal(docs.groups([{...pending,verification_status:'Verified'},old])[0].current.id,'new');assert.equal(docs.groups([pending,old])[0].history.length,2);});
test('expiry boundaries and no untrusted executable file links',()=>{assert.equal(docs.expiry('2026-09-27','2026-09-28'),'Expired');assert.equal(docs.expiry('2026-09-28','2026-09-28'),'Due within 30 days');assert.equal(docs.safeURL('javascript:alert(1)'), '');assert.equal(docs.safeURL('https://evil.example/paper'), '');});
test('document requires pages, expiry decision and allowed file formats',()=>{assert.throws(()=>docs.validate(valid,[],['OD05AP9537'],[]),/Add/);assert.throws(()=>docs.validate({...valid,no_expiry:false},[photo],['OD05AP9537'],[]),/validity/);assert.throws(()=>docs.validate(valid,[{blob:new Blob(['svg'],{type:'image/svg+xml'})}],['OD05AP9537'],[]),/JPG/);});
function fixture(){const records=new Map();let deny=false;const api={db:{},collectionName:'records',doc:(_,c,id)=>id,serverTimestamp:()=>123,storage:{},storageRef:(_,p)=>p,uploadBytes:async()=>{if(deny)throw Error('Storage denied');},getDownloadURL:async p=>'https://firebasestorage.googleapis.com/'+p,allowed:()=>({vehicles:['OD05AP9537'],drivers:['Somnath']}),actor:()=> 'Somnath',isAdmin:()=>false,runTransaction:async(_,fn)=>fn({get:async id=>({exists:()=>records.has(id),data:()=>records.get(id)}),set:(id,r)=>records.set(id,r),update:(id,r)=>records.set(id,{...records.get(id),...r})})};return {records,api,deny:()=>deny=true};}
test('failed upload never creates metadata or claims success',async()=>{const f=fixture();f.deny();await assert.rejects(store.create(f.api).save(valid,[photo],'abc'),/Storage denied/);assert.equal(f.records.size,0);});
test('retry creates one record and never resets verified status',async()=>{const f=fixture(),s=store.create(f.api);await s.save(valid,[photo],'abc');f.records.get('VEHICLE_DOC_abc').verification_status='Verified';await s.save(valid,[photo],'abc');assert.equal(f.records.size,1);assert.equal(f.records.get('VEHICLE_DOC_abc').verification_status,'Verified');await assert.rejects(s.review('VEHICLE_DOC_abc','Rejected'),/Office/);});
